### ISSUE TITLE
Fixnum is deprecated  

### ISSUE THREAD

**Issue by efranco89** [sevenwire/forgery#82] opened 2017-04-06 21:38 UTC
/home/efranco/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/forgery-0.6.0/lib/forgery/forgery/lorem_ipsum.rb:51: warning: constant ::Fixnum is deprecated

**Comment by franklinyu** [comment] 2017-11-14 17:09
Duplicate of #79

**Comment by brandonarbini** [comment] 2017-12-05 06:43
Fixed by #84.

**Closed by brandonarbini** 2017-12-05 06:43 UTC
